--USUÁRIO ADMIN:
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE funcionario TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Empresa TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE rotas TO admin;

