# .streamlit/config.toml

[theme]
base="light"  # Usar tema claro como base
primaryColor="#1E90FF"  # Azul para botões, etc.
backgroundColor="#87CEEB"  # Azul claro para fundo
secondaryBackgroundColor="#F0F0F0"  # Cinza claro para fundo secundário
textColor="#000000"  # Preto para texto
font="sans serif"  # Fonte sem serifa
